import turtle

window=turtle.Screen()
myTurtle=turtle.Turtle()
screen=myTurtle.getscreen()
screen.title("Mutlu Yıllar")
screen.bgcolor("#d8bfd8")

myTurtle.color("green")
myTurtle.pensize(5)
myTurtle.begin_fill()
myTurtle.forward(200)
myTurtle.left(150)
myTurtle.forward(180)
myTurtle.right(150)
myTurtle.forward(120)
myTurtle.left(150)
myTurtle.forward(120)
myTurtle.right(150)
myTurtle.forward(80)
myTurtle.left(150)
myTurtle.forward(200)

myTurtle.left(60)
myTurtle.forward(200)
myTurtle.left(150)
myTurtle.forward(80)
myTurtle.right(150)
myTurtle.forward(120)
myTurtle.left(150)
myTurtle.forward(120)
myTurtle.right(150)
myTurtle.forward(180)
myTurtle.left(150)
myTurtle.forward(266)
myTurtle.end_fill()

myTurtle.color("#d2b48c")
myTurtle.pensize(2)
myTurtle.begin_fill()

myTurtle.right(90)
myTurtle.forward(70)
myTurtle.right(90)
myTurtle.forward(33)
myTurtle.right(90)
myTurtle.forward(70)
myTurtle.end_fill()

myTurtle.speed(2)
myTurtle.penup()
myTurtle.color("yellow")
myTurtle.goto(-36,230)
myTurtle.begin_fill()
myTurtle.pendown()
for i in range(5):
    myTurtle.forward(40)
    myTurtle.right(144)
myTurtle.end_fill()

def ball (trt,x,y,size=10,colour="red"):
    trt.penup()
    trt.setpos(x,y)
    trt.color(colour)
    trt.begin_fill()
    trt.pendown()
    trt.circle(size)
    trt.end_fill()
ball(myTurtle,175,-5,colour="yellow")
ball(myTurtle,135,80,colour="pink")
ball(myTurtle,135,140,colour="purple")
ball(myTurtle,-180,140,colour="#ffff00")
ball(myTurtle,-190,80,colour="#daa520")
ball(myTurtle,-230,-5,colour="#7cfc00")
ball(myTurtle,40,100,size=4,colour="blue")
ball(myTurtle,15,200,size=5,colour="#66cdaa")
ball(myTurtle,-25,135,size=7,colour="orange")
ball(myTurtle,-65,60,size=8,colour="#db7093")
ball(myTurtle,-110,-5,size=6,colour="#7fffd4")
ball(myTurtle,-110,140,size=5,colour="#7fffd4")
ball(myTurtle,40,40,size=8,colour="#ffff00")
ball(myTurtle,-120,40,size=9,colour="#daa520")
ball(myTurtle,-100,180,size=6,colour="#7cfc00")
def gift(g,x,y,size=40,colour="red"):
    g.speed(2)
    g.penup()
    g.color(colour)
    g.goto(x,y)
    g.begin_fill()
    g.pendown()
    for i in range(4):
        g.forward(size)
        g.right(90)
    g.end_fill()

gift(myTurtle,50,-80,size=50,colour="#f0e68c")
gift(myTurtle,80,-80,size=30,colour="#fafad2")
gift(myTurtle,120,-80,size=25,colour="#32cd32")
gift(myTurtle,-120,-80,size=63,colour="#ffd700")

myTurtle.speed(1)
myTurtle.penup()
m="Mutlu Yıllar"
myTurtle.goto(0,-200)
myTurtle.color("white")
myTurtle.pendown()
myTurtle.write(m,move=False,align="center",font=("Arial",20,"bold"))
myTurtle.hideturtle()
window.mainloop()
